apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
        - name: app
          image: ghcr.io/folivorra/ci/cd_app:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-login
