name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: docker check
      run: docker --version

    - name: build docker image
      run: docker build -t my-app .